spring.application.name=api

# PostgreSQL datasource (configured for remote host provided)
spring.datasource.url=jdbc:postgresql://85.247.43.227:5432/pcmr
spring.datasource.username=diogo
spring.datasource.password=1234
medicao.duracao-segundos=30

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MQTT topics
MQTT_TOPIC_SENSORS=sensors/#
MQTT_TOPIC_BIOMETRIA=casa/biometria/acesso
MQTT_TOPIC_COMANDO=casa/biometria/comando
MQTT_CIPHER_KEY=y1RpGJ0lRkxFEB29C7qmJ0KU2u8skiwrKwWWpj+jyGs=
# openssl rand -base64 32