spring.application.name=api

# spring.datasource.url=jdbc:postgresql://localhost:5432/pcmr
spring.datasource.url=jdbc:postgresql://192.168.1.77:5432/pcmr
spring.datasource.username=pcmr
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
